config/routes.rb
Rails.application.routes.draw do
  root 'trip_planner#index'
  get 'trip_planner/index'
  post 'trip_planner/trip_planning'
  get 'trip_planner/display_route'
  
  get 'dropPins'=>'layers#dropPins'
  
  get '/auth/:provider/callback', :to =>  'sessions#create'
  get 'auth/failure', to: redirect('/')
  get '/logout', :to => 'sessions#destroy'
  
  get 'auth_failure' => 'sessions#auth_failure'

  resources :routes
  resources :trips
  resources :stops
  resources :stop_times
  resources :calendar_dates
  resources :calendars
  resources :points
  
  resources :cars
  resources :buildings
  resources :users
  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/trip_planner_controller.rb
require 'geocoder'
require 'set'
require 'google_maps_service'

class TripPlannerController < ApplicationController
  
  @@gmaps = GoogleMapsService::Client.new()
  # @@gmaps.key = "AIzaSyAOoWZdZFz8nFtVjBlWRysnSoSoSguqCII"
  @@gmaps.key = "AIzaSyBGXhzWszzxqmajf5w0AzEmFi5hbgA8VRY"

  def index
    
  end
  
  def trip_planning
    # convert from array to array of strings
    @path = bus_route_planning(params[:trip_planner][:from], params[:trip_planner][:to])
    #@path = []
    #@path_raw.each do |curr_point|
      #@path << (curr_point[0].to_s + "," + curr_point[1].to_s)
    #end
    session[:path] = @path;
    redirect_to trip_planner_display_route_path
  end

  def display_route
    #path1 = {:transportation_type => "walk", :nav_points => [{:lat => 30.6139, :lng => -96.3397},{:lat => 30.6111668414573, :lng => -96.3236662044326}]}.to_json
    #path2 = {:transportation_type => "bus", :bus_route_name => "26", :nav_points => [{:lat => 30.6111668414573, :lng => -96.3236662044326},{:lat => 30.6091645723083, :lng => -96.3209303510744},{:lat => 30.6118387348556, :lng =>  -96.3184291910189}]}.to_json
    render json: session[:path]  if request.xhr?
  end
  
  def address_to_coordinates (address)
    # Call geocode and return coordinates
    # the coordinates returned is [lan_value, lon_value]
    geocoder_results = Geocoder.search(address)
    unless geocoder_results.empty?
      coordinates = geocoder_results[0].coordinates
      return coordinates
    end
    return nil
  end
  
  def find_available_stops(time)
    available_stops = Array.new
    bus_routes = Route.all

    bus_routes.each do |curr_route|
      #route_available = false
      curr_route_trips = curr_route.trips.select("calendar_id").distinct
      curr_route_trips_full = curr_route.trips
      curr_route_trips.each do |a_trip|
        if available?(a_trip, time)
          curr_route_trips_full.select{|m| m.calendar_id == a_trip.calendar_id}
          #route_available = true
          available_stops += curr_route_trips_full[0].stops
          break
        end
      end
        
      
      # if route_available
        
      # end
    end
    return available_stops.uniq
  end
  
  # def stop_available?(stop, time)
  #   trips = stop.trips.distinct
  #   trips.each do |each_trip|
  #     if available?(each_trip, time)
  #       return true
  #     end
  #   end
  #   return false
  # end
  
  def find_nearest_stop (raw_coordinates, time)
    # Return a nearest statio
    
    stops = find_available_stops(time)
    #stops = Stop.all
    min_distance = Float::INFINITY
    nearest_stop = nil
    stops.each do |curr_stop|
      curr_stop_coordinates = [curr_stop.lan, curr_stop.lon]
      distance = Geocoder::Calculations.distance_between(curr_stop_coordinates, raw_coordinates)
      #if distance < min_distance and stop_available?(curr_stop, time)
      if distance < min_distance
        min_distance = distance
        nearest_stop = curr_stop
      end
    end
    return nearest_stop
  end
  
  def walking_route(depart_coordinates, destination_coordinates)
    # Return a walking route object
    route = @@gmaps.directions(depart_coordinates, destination_coordinates, mode: 'walking', alternatives: false)
    unless route.empty?
      return route[0]
    end
    return nil
  end
  
  def path_from_google_route(route)
    # Contains all points that define a google path
    path_points = []
    all_steps = route[:legs][0][:steps]
    all_steps.each do |curr_step|
      curr_coordinates = [curr_step[:start_location][:lat], curr_step[:start_location][:lng]]
      path_points << curr_coordinates
    end
    last_coordinates = [route[:legs][0][:end_location][:lat], route[:legs][0][:end_location][:lng]]
    path_points << last_coordinates
    return path_points
  end
  
  def available?(trip, time)
    curr_calendar = Calendar.find(trip.calendar_id)
    week_day = time.strftime('%A').downcase
    # Currently all elements in calendar are zero, so we use one as "true"
    truth_condition = 1
    general_availability = (curr_calendar.send(week_day) == truth_condition)
    curr_date = Date.new(time.year, time.month, time.day)
    within_service_period = curr_calendar.start_date <= curr_date and curr_calendar.end_date >= curr_date
    exception_schedule = Calendar_date.where(date:(curr_date))
    
    is_exception = false
    if not exception_schedule.empty?
      if (exception_schedule.pluck(:calendar_id).include?(trip.calendar_id))
        is_exception = true
      end
    end
    return (is_exception or (general_availability and within_service_period))
  end
      
  
  def find_routes_set_by_stop(stop, time)
    # Return a set which contains all routes including input stop
    # routes_set = Array.new 
    # bus_routes = Route.all
    # bus_routes.each do |curr_route|
    #   curr_route_stops = curr_route.trips[0].stops.distinct
    #   if(curr_route_stops.include?(stop))
    #     routes_set.push(curr_route)
    #   end
    # end
    # return routes_set
      routes_set = Array.new
      bus_routes = Route.all

      bus_routes.each do |curr_route|
        route_available = false
        has_stop = false
        curr_route_trips = curr_route.trips.select("calendar_id").distinct
        
        curr_route_trips.each do |a_trip|
          if available?(a_trip, time)
            route_available = true
            break
          end
        end
          
        curr_route_stops = curr_route.stops.select("code").distinct
        codes = curr_route_stops.map {|t| t.code}
        has_stop = (codes.include?(stop.code))
        # puts "route_available\n", route_available, "\n", "has_stop\n", has_stop
        if (has_stop and route_available)
          routes_set.push(curr_route)
        end
      end
      return routes_set
  end
  
  def euclidean_distance(vector1, vector2)
    sum = 0
    vector1.zip(vector2).each do |v1, v2|
      component = (v1 - v2)**2
      sum += component
    end
    Math.sqrt(sum)
  end
  
  # Find the bus path between depart and destination stop given a certain bus route
  def find_path(route, depart_stop, destination_stop)
   
    depart_stop_coordinates = [depart_stop.lan, depart_stop.lon]
    destination_stop_coordinates = [destination_stop.lan, destination_stop.lon]
    mini_distance_depart = Float::INFINITY
    mini_depart_point = nil
    mini_distance_destination = Float::INFINITY
    mini_destination_point = nil
    destination_stop_coordinates = [destination_stop.lan, destination_stop.lon]
    all_path_points = Point.where(shape_id:(route.trips[0].shape_id)).order(:pt_sequence)
    all_path_points.each do |path_point|
      path_point_coordinates = [path_point.pt_lan, path_point.pt_lon]
      distance_depart = Geocoder::Calculations.distance_between(path_point_coordinates, depart_stop_coordinates)
      distance_destination = Geocoder::Calculations.distance_between(path_point_coordinates, destination_stop_coordinates)
      if(mini_distance_depart > distance_depart)
        mini_distance_depart = distance_depart
        mini_depart_point = path_point
      end
      if(mini_distance_destination > distance_destination)
        mini_distance_destination = distance_destination
        mini_destination_point = path_point
      end
    end
    
    path_points = []
    # If the depart point is ahead of the destination point, then just return the path between them, the path may
    # be something like (start point)2->3->4->5(end point).
    # But if the destination point has a smaller sequence id than the depart point, this means that in fact,
    # You need to first go to the final stop, and then start from the final stop (now become the first stop),
    # And then go to the destination point. In this case the path may be something like:
    # (start point)5->6/1(final/start point)->2(end point)
    if mini_depart_point.pt_sequence < mini_destination_point.pt_sequence
      path_points = all_path_points[mini_depart_point.pt_sequence..mini_destination_point.pt_sequence]
    else
      path_points += all_path_points[mini_depart_point.pt_sequence..-1]
      path_points += all_path_points[1..mini_destination_point.pt_sequence]
    end
    raw_point_coordinates = []
    path_points.each do |curr_point|
      raw_point_coordinates << [curr_point.pt_lan, curr_point.pt_lon]
    end
    return raw_point_coordinates
  end
  
  # Depart_address: string for start address
  # Destination_address: string for destination address
  # Return the path containing all coordinate points, representing the best path
  def bus_route_planning (depart_address, destination_address)
    time = Time.now.getlocal('-06:00')
    depart_coordinates = address_to_coordinates(depart_address)
    destination_coordinates = address_to_coordinates(destination_address)
    depart_stop = find_nearest_stop(depart_coordinates, time)
    destination_stop = find_nearest_stop(destination_coordinates, time)
    
    depart_stop_coordinates = [depart_stop.lan, depart_stop.lon]
    #depart_walking_route = walking_route(depart_coordinates, depart_stop_coordinates)
    destination_stop_coordinates = [destination_stop.lan, destination_stop.lon]
    #destination_walking_route = walking_route(destination_stop_coordinates, destination_coordinates)
    
    # This set contains all routes including the departing stop 
    routes_containing_depart = find_routes_set_by_stop(depart_stop,time)
    # This set contains all routes including the destination stop 
    routes_containing_destination = find_routes_set_by_stop(destination_stop,time)
    # This array defines the shape of the routing results, it contains multiple coordinates
    final_path_points = []
   # final_path_points += path_from_google_route(depart_walking_route)
    hash_depart={:lat =>depart_coordinates[0],:lng =>depart_coordinates[1]}
    hash_first_stop={:lat =>depart_stop_coordinates[0],:lng =>depart_stop_coordinates[1]}
    walking_path={:transportation_type =>"walk", :nav_points => [hash_depart,hash_first_stop]}

app/helpers/trip_planner_helper.rb
module TripPlannerHelper
end

app/views/trip_planner/_banner.html.haml
%body
  / Navigation
  %nav.navbar.navbar-default.navbar-fixed-top
    .container-fluid
      .navbar-header
        %button.navbar-toggle.collapsed{"data-target" => "#navbar1", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "http://www.tamu.edu"}
          %img{:src => "http://brandguide.tamu.edu/images/tam-primarymark.png", :width=>"228", :height=>"45"}/
      #navbar1.navbar-collapse.collapse
        %ul.nav.navbar-nav{:id => 'leftMenu'}
          %li
            %a{"data-toggle" => "modal", :href => "#dir", :onclick => "#dir"} 
              %span.glyphicon.glyphicon-move
              Directions
          %li
            %a{"data-toggle" => "modal", :href => "#layer"} 
              %span.glyphicon.glyphicon-menu-hamburger
              Layers
        - if current_user
          %ul.nav.navbar-nav.navbar-right
            %li
              %img{:src => current_user.image_url,:height => "42", :width => "42"}/
            %li
              %a{:href => logout_path}
                Log out
        - else
          %ul.nav.navbar-nav.navbar-right
            %li
              %a{"data-toggle" => "modal", :href => "#login", :style => "align: center"}
                %span.glyphicon.glyphicon-log-in
                Login
      / /.nav-collapse
    / /.container-fluid
  #login.modal.fade{:role => "dialog"}
    #loginDlg.modal-dialog
      .modal-content
        .modal-header
          %h4.modal-title Login
        .loginStyle
          #loginImg.form-group
            %a.navbar-brand{:href => "/auth/twitter"}
              %img{:src => "http://cdn.androidbeat.com/wp-content/uploads/2014/11/image-Twitter-logo.png", :width=>"35", :height=>"35", :class => "style_image"}/
            %a.navbar-brand{:href => "/auth/google_oauth2"}
              %img{:src => "http://www.presidentialpressurewashing.net/sitebuilder/images/Red-signin-Small-press-44dp-120x120.png", :class => "style_image", :width=>"35", :height=>"35"}/
  #dir.modal.fade.modeless{:role => "dialog", "data-backdrop" => "false"}
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Trip planner
      .modal-body
        %form{:id=>"directionsForm"}
          %label.radio-inline
            %input{:name => "optradio",:value => "Bike",:type => "radio", :checked => "checked"}/
            Bike
          %label.radio-inline
            %input{:name => "optradio",:value => "Driving",:type => "radio"}/
            Driving
          %label.radio-inline
            %input{:name => "optradio",:value => "Transit",:type => "radio"}/
            Transit
          %label.radio-inline
            %input{:name => "optradio",:value => "Walking",:type => "radio"}/
            Walking
        = form_tag trip_planner_trip_planning_path,:id => "directionsInputForm",:method => :post do
          = label :trip_planner, :from, "From:"
          = text_field :trip_planner, :from, class:'form-control', :id=> 'fromDirection', :required => true
          = label :trip_planner, :to, "To:"
          = text_field :trip_planner, :to, class:'form-control', :id=> 'toDirection', :required => true
          %br
          = submit_tag 'Find Directions', class: 'btn btn-default', id: 'findDirections'
          %button.btn.btn-default.pull-right{:id => "clearDirections"} Clear Directions
      .modal-footer{:id => "results",:style => "overflow-y: auto; max-height: 250px; text-align: left;"}
        %h5 No Results
  #layer.modal.fade.modeless{:role => "dialog", "data-backdrop" => "false"}
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Layers
      .modal-body
        %form{:id=>"searchForm"}
          .form-group
            %label.custom-control.custom-checkbox
              %input.custom-control-input{:id=>"Bikes", :name => "layer[bicycle]", :type => "checkbox", :value => "1", :onclick => "toggleMarkers(this);"}/
              %span.custom-control-indicator
              %span.custom-control-description Bicycle Racks
          .form-group
            %label.custom-control.custom-checkbox
              %input.custom-control-input{:id=>"Building", :name => "layer[building]", :type => "checkbox", :value => "1", :onclick => "toggleMarkers(this);"}/
              %span.custom-control-indicator
              %span.custom-control-description Academic Buildings
          .form-group
            %label.custom-control.custom-checkbox
              %input.custom-control-input{:id=>"Parking",:name => "layer[parking]", :type => "checkbox", :value => "1", :onclick => "toggleMarkers(this);"}/
              %span.custom-control-indicator
              %span.custom-control-description Parking Lots

app/views/trip_planner/display_route.html.haml
= render :partial => 'banner'

#right-panel
#map

  :javascript
    var apiKey = 'AIzaSyAOoWZdZFz8nFtVjBlWRysnSoSoSguqCII';
    var map;
    var snappedCoordinates = [];
    var placeIdArray = [];
    
    function initMapNew() {
        var tamuCenter = {lat: 30.6187199, lng: -96.3364829};
    
        map = new google.maps.Map(document.getElementById('map'), {
            zoom: 15,
            center: tamuCenter,
    	      mapTypeControlOptions: {
                style: google.maps.MapTypeControlStyle.HORIZONTAL_BAR,
                position: google.maps.ControlPosition.TOP_RIGHT
            }
          });
       }
      
    //var qd = {};
    //location.search.substr(1).split("&").forEach(
            //function(item) {var s = item.split("="), k = s[0], v = s[1] && decodeURIComponent(s[1]); (qd[k] = qd[k] || []).push(v)})
    function display() 
    {
        initMapNew();
        $.ajax({url: 'display_route',
               dataType: 'json',
               timeout: 5000,
               success: function(data) { draw_route(data); }
               });
        // the new front end function:
        // runGNavigation(qd['path%5B%5D']);
        // runSnapToRoad(qd['path%5B%5D']);

    }
    
    function draw_route(data) 
    {
      var i;
      for(i = 0; i < data.length; i++) 
      { 
        path = data[i];
        switch(path.transportation_type) {
          case "walk":
            runGNavigation(path.nav_points);
            break;
          case "bus":
            runSnapToRoad(path.nav_points.map(toString), path.bus_route_name);
            displayBusInformation(path.nav_points, path.bus_route_name);
        }
      }
    }
    
    function toString(latlon) 
    { 
      result = "" + latlon.lat + ", " + latlon.lng;
      return result;
    }
    
    function runGNavigation(data)
    {
      start = data[0];
      end = data[1];
      
      startToEnd = {
        origin:  start,
        destination: end,
        travelMode: 'WALKING'
      };
      
      var directionsService = new google.maps.DirectionsService;
      var directionStartToEnd = new google.maps.DirectionsRenderer({
        map: map,
        polylineOptions : {
          strokeColor:'green',
          strokeOpacity: 0.7,
        },
        //suppressMarkers: true
      });
      
      directionsService.route(startToEnd, function(response, status) {
        if (status === 'OK') {
          directionStartToEnd.setDirections(response);
          var route = response.routes[0];
          var walk_latlng=[];
          var instructionArr=[];
          
            for (var i =0; i < response.routes[0].legs[0].steps.length; i++){
                //instructionArr.push(response.routes[0].legs[0].steps[i].instructions);
                walk_latlng.push(
                {
                  lat: response.routes[0].legs[0].steps[i].start_point.lat(),
                  lng: response.routes[0].legs[0].steps[i].start_point.lng()
                }
                )
            }
            
            instructionArr.push('Walking takes ' + response.routes[0].legs[0].duration.text);
            add_markers(walk_latlng, "Walking", instructionArr, false);
          
        } else {
          window.alert('Directions request failed due to ' + status);
        }
      });
    }

    function runSnapToRoad(path, route_name) {  
      $.get('https://roads.googleapis.com/v1/snapToRoads', {
        interpolate: true,
        key: apiKey,
        path: path.join('|')
      }, function(data) {
        processSnapToRoadResponse(data);
        drawSnappedFullPolyline(route_name);
      });
    }
    
    function displayBusInformation(points, route_name){
      var instructionArr=[];
      var time = 1;
      instructionArr.push("Taking bus #"+ route_name + " might take " + time*points.length+ " mins");
      add_markers(points, route_name, instructionArr, false) 
      add_markers(points.slice(0, Math.floor(points.length/2)), route_name, instructionArr, true)

    }
    
    // Store snapped polyline returned by the snap-to-road service.
    function processSnapToRoadResponse(data) {
      snappedCoordinates = [];
      placeIdArray = [];
      for (var i = 0; i < data.snappedPoints.length; i++) {
        var latlng = new google.maps.LatLng(
            data.snappedPoints[i].location.latitude,
            data.snappedPoints[i].location.longitude);
        snappedCoordinates.push(latlng);
        placeIdArray.push(data.snappedPoints[i].placeId);
      }
    }
    
    function getColorForRoute(route_name) {
      route_name = route_name.replace(/\D/g,'')
      var myColors = ['#d59563', '#d59563', '#263c3f','#6b9a76', '#38414e' ,'#212a37','#9ca5b3', '#746855', '#1f2835', '#f3d19c', '#2f3948', '#d59563', '#17263c','#515c6d', '#17263c', 'purple', 'red', 'orange','yellow'];
      var ind =  Math.floor(Number(route_name)%myColors.length);
      return myColors[ind];
    }
    
    function drawSnappedFullPolyline(route_name){
      //console.log(placeIdArray.length/100)
      //for (var i = 0; i <= Math.floor(placeIdArray.length / 100); i++){
      //  var start = i * 100;
     //   var end = Math.min((i+1)*100, placeIdArray.length);
     //   console.log(start)
      //  console.log(end)
        drawSnappedPolyline(route_name); //, start, end);
      //}
    }

    
    // Draws the snapped polyline (after processing snap-to-road response).
    function drawSnappedPolyline(route_name, mystart, myend) {
      var color = getColorForRoute(route_name);
      var coords = snappedCoordinates;
      
      var snappedPolyline = new google.maps.Polyline({
        path: coords,
        strokeColor: color,
        strokeWeight: 3
      });
    
      snappedPolyline.setMap(map);
      //polylines.push(snappedPolyline);
    }
    
    function add_markers(points, route_name, instructions, flag) {  
      var text = [];
      if(flag){
        text = "Bus route:" + route_name;
      }
      else{
        text = instructions[0];
      }

      var infowindow = new google.maps.InfoWindow({
        content: text
      });
         
      var ind = Math.floor(points.length/2);
      var marker = new google.maps.Marker({
        position: points[ind],
        map: map,
        title: route_name
      });
        
      marker.addListener('click', function() {
        infowindow.open(map, marker);
      });
    }
  %script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyBGXhzWszzxqmajf5w0AzEmFi5hbgA8VRY&callback=display"}
  :cdata

app/views/trip_planner/index.html.haml
= render :partial => 'banner'

#map
  %script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyBGXhzWszzxqmajf5w0AzEmFi5hbgA8VRY&libraries=places&callback=initMap"}